### ISSUE TITLE
outputting .Rmd files to html vs. md/github

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#1]
Crystal - 

thanks for your comments regarding .md/html files

I just activated github pages for rclass2 repository

between the two options you specify (github pages or link to html in the README.md for each lecture), I think I like the github pages opiton. as you say, keeps everything in one place.

I think something w/ functionality of the rclass website for the intro r class (https://ozanj.github.io/rclass/ ) and similar feel/organization to Skinner's course (https://edquant.github.io/edh7916/)

likely, the github pages website is something we will want regardless.

but before we make final decision on the html output issue, wanted to get your thoughts. do you think html_document output is the way to go? the *principal* reason I like html_document is that it can number table of contents/sections, so the feel is similar to online books like "r for data science" https://r4ds.had.co.nz/transform.html 

I think the numbering is helpful for students. but what do you all think?

**Comment by cyouh95** [comment]
I think I agree - html_document output will probably be the output in this case!

Or, if you like the structure of the `R for Data Science` book, maybe bookdown is another option? According to the [documentation](https://bookdown.org/yihui/bookdown/usage.html), the pages are generated directly from `.Rmd` files. For example, [this page](https://r4ds.had.co.nz/transform.html) comes from [this](https://github.com/hadley/r4ds/blob/master/transform.Rmd).

**Comment by ozanj** [comment]
I asked Will Doyle about using bookdown [for same reason that you did]

he used bookdown to create his first "data science w/ R" course.

but he said he didn't like it and stopped using bookdown for subsequent iterations of the course. long story short, in a course like this there is a lot of tweaking of files as you correct errors, figure out better ways of explaining things. and apparently bookdown is cumbersome for making lots of changes like this.

so lets go w/ html_output and @cyouh95 and @mpatricia01 you two can figure out best way to post the html files, probably using github pages.

**Comment by mpatricia01** [comment]
Hi @ozanj and @cyouh95 ! 

I agree with html_output and Crystal and I can set up a meeting to discuss best way to post html files.

**Comment by ozanj** [comment]
html files on class website.
