### ISSUE TITLE
removing comma with str_ replace

### ISSUE THREAD

**Issue by clemencedarriet** [Rucla-ed/rclass2#102]
Hello! 
Anyone know how to remove the pesky comma from code:

str_replace_all(locations,"([:alpha:]+\\s[:alpha:]+[:punct:]\\s)([:upper:]{2}\\s)([:digit:]{5})","\\1 has a zipcode \\3 and is in the state \\2")

this is my output:
Los Angeles,  has a zipcode 90024 and is in the state CA

thanks! @ozanj @cyouh95 @mpatricia01

**Comment by cyouh95** [comment]
@clemencedarriet Remember that not everything you write in your regex needs to be within a pair of parenthesis (ie. capturing group). If you try moving the `[:punct:]\s` part to be outside of the first pair of parenthesis, then it won't show up in your output when you're referencing `\\1`. Hope this helps!

**Comment by clemencedarriet** [comment]
Yes that worked! Thank you so much!
