### ISSUE TITLE
Webscraping data from FB? 

### ISSUE THREAD

**Issue by ecp9** [Rucla-ed/rclass2#108]
I was wondering if we can use similar methods to web-scrape data from Facebook groups (w/o any identifiable information of the user--I'm interested in scraping posts in a FB group). However, it was brought up to me that there are ethical issues that come with this. I wonder if this is at all possible (given the Cambridge Analytica scandal) and what are some ethical issues that arise with web-scraping posts on either twitter or FB?

**Comment by ecp9** [comment]
@ozanj @mpatricia01

**Comment by ecp9** [comment]
I'm also looking for suggested readings on the ethics of webscraping data if anyone has any articles that would be helpful!

**Comment by ozanj** [comment]
My understanding is that facebook's legal team aggressively prohibits and policies scraping of data from fb. perhaps in part as a response to past scandals. @nfhavey said a bit about this in a reply to issue #98

in general, my understanding is that when an API does not exist [cuz a company does not want to make it easy to get their data] it is usually technically feasible to scrape the data, but the company's legal team may prohibit and police scraping, effectively eliminating your ability to scrape. 

With respect to the ethics of web-scraping, see below description of upcoming course from Safiya Noble, UCLA prof of Information Studies. the course is about the broader issue of data ethics in the age of data science and big-tech-big-brother. I'm not sure when it is being offered but will pass on info if/when I find out

*****

Course Title: Data, Ethics and Justice in Society
Short Title: Data Ethics
Units: 5
Grading: Letter
Instructional Format: Seminar 4 hours/Discussion 1 hour
GE Requirement: NO
No prerequisites
Course Description: In this course, we will explore the moral, social, political, and ethical ramifications of the choices we make at the different stages in the social construction of data. This will include cultivating a critical analysis of processes of data collection, data mining, data storage and the deployment of data affected by a variety of different communities, publics, nation-states, and individuals. Students will learn the basics of ethical and socially just frameworks to assess a range of data-driven projects and platforms. Students will develop an acute understanding of the social, historical, and political dilemmas of big data, algorithmic decision-making, predictive analytics, and the distinct challenges associated with ethical, civil-, human- and sovereign-rights models of engaging the modern digital information era.
Instructor: Safiya Noble, Ph.D., Department of Information Studies

**Comment by ecp9** [comment]
Thank you @ozanj !
