### ISSUE TITLE
problem sets and new student repositories

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#11]
I am checking into whether students who are "Members" of the org Rucla-ed can create private repositories within the org.

The rationale is that for students to really be learning how to use git/github, I think they need to do more than just complete the problem set in their student_lastname repositories and then have us pull the repository and check their homework. 

rather, to learn git/github, I think they need to be creating repositories [on github or on local machine], connecting local and remote repositories, then doing the real work [writing R code] in their local working directory, adding/committing this to local repository, and pushing to remote repository. then, since we are admin for the org, we should be able to have full control over these private repositories created by students for problem sets.

so I created a new github account called ozanburner. 

I invited ozanburner to be a member of Rucla-ed.

I logged into github as ozanburner, went to the Rucla-ed org, and then created a new private repository called ozanburner_ps1 and did initial commit w/ README. 

Then I cloned ozanburner_ps1 to my local machine [still logged in as ozanburner]. 

Next, on my local machine using git bash, I tried, changing files, adding files, committing them, pushing them. that worked fine, but the problem I ran into was git bash thinks I am the github user ozanj rather than the github user ozanburner. so once I pushed changes, this was a commit from ozanj rather than ozanburner. 

I *think* I could get over this by adding multiple ssh to git/github, as described here:
https://www.freecodecamp.org/news/manage-multiple-github-accounts-the-ssh-way-2dadc30ccaca/

but I didn't have time to go through all that.

anyways, when go to Rucla-ed and look at "people" ozanburner is "admin" on ozanburner_ps1 repository and "read" on all other repositories in the org. by contrast, @ozanj @mpatricia01 @cyouh95  are "admin" on all repositories, including ozanburner.

looong story short, for problem set 1, we could have students create a new repository (e.g., lastname_ps1), connect local to remote repository, do some basic tasks in R from local working directory, add/commit changes to local repository, push to remote repository.

Then grading could be done directly on github.com or by pulling those lastname_ps1 repositories to your local machine. 

Once students get into teams (e.g., for PS2), they could create one repository per team (but initially, maybe separate .Rmd files for each team member), and then you would be pulling 8 repositories rather than 22.

it is a little more work for you Patricia than having students just do problem sets on their student_lastname repositories. maybe there is a way a script can be written to batch pull multiple repos?

the main issue here though, is that if we want students to actually learn how to use git and github [especially for bulk of quarter when they will be doing problem sets in groups of 3], then I don't see how they can really learn this stuff if they aren't creating/changing their own repos. 

The grm solution is an efficient way to have all students have an updated copy of rclass2 repo on their local machine. But w/ respect to submitting problem sets, it seems to take out all the "doing stuff in git/github" that would be essential for learning. 

What do you three think about this?

**Comment by cyouh95** [comment]
Maybe I'm missing something, but w/ the student_lastname repos created by grm, shouldn't students also be able to change their own repos? (ie. add files, commit, push) 

So the only additional step they would do if they were to create their own repo from scratch is this [first part on Github](https://help.github.com/en/github/getting-started-with-github/create-a-repo), where they initialize the repo w/ a README. After that, they can `git clone new_repo`, similar to what they would've done w/ the grm private repo (`git clone student_lastname`). And in both cases, they can proceed to add files/commit/push in the same way... or is there something else the student_lastname repo can't do?

**Comment by ozanj** [comment]
What about when students start working in groups of 3? Think it would be
good practice for them to be working on same repo

**Comment by cyouh95** [comment]
I think the team repos sounds like a good idea - will this be replacing their student_lastname repos once they start working in groups of 3?

And when they work on the team repo, will they be working on same .Rmd file and submitting 1 problem set per team? If so, maybe lecture should also cover how to resolve merge conflicts at some point, just in case.

Github lecture should also probably cover issues in more detail if we'll be doing #13? Let me know if there's anything I could help w/ on the lecture revisions!

**Comment by ozanj** [comment]
@cyouh95 @mpatricia01 

when they start working in groups, I think they would make a new repo for each problem set (e.g., teamname_ps2, teamname_ps3). the reason is, I think getting used to the process of creating new repos will make them feel much more comfortable w/ git and github. initially, when they are working in teams, I think each team member should have their own scripts (e.g., lastname_ps2) within the "scripts" sub-directory and they could share common stuff like datasets in a data directory.

I am still leaning towards everyone creating their own repo for ps1. it is only 10-15 minutes of work to pull all these repos.

**Comment by ozanj** [comment]
think this is closed.
