### ISSUE TITLE
R script too long? Scrolling too much? Use an outline!

### ISSUE THREAD

**Issue by augias** [Rucla-ed/rclass2#120]
Hi all, a colleague of mine mentioned a cool Rstudio feature when you R script file starts getting very long: Outlines! 

![Rstudio](https://user-images.githubusercontent.com/19480035/82850429-34c5ce00-9eb1-11ea-9aa3-dcc6a07d9692.png)

If you click on buttons on the far right top panel of the script panel, or on the bottom left of the script panel, you see an outline of every "section" of your R code. Rstudio parses a section automatically any time you write a comment ending in at least four dashes or # signs. 
(i.e., # Section 1 ----  -or- # Section 1 ####)

You can even collapse sections you're not busy working on to cut down on distractions.
This blog post has some easy shortcuts: https://www.natedayta.com/2019/12/25/owning-outlines-in-rstudio/

**Comment by ozanj** [comment]
Thanks for this Fern!

I read the blog post you linked. very helpful. does all functionality of outlines work for both .Rmd files and .R scripts?

**Comment by augias** [comment]
It does, but seems to follow R markdown's own logic for headers, where #, ##, ### mark sections and subsections the same as the html or pdf outputs. No trailing dashes or pound signs needed on an rmd. 

This is great for when I'm following along in a lecture, move to the rmd and need to navigate to the right section to run a code chunk in the markdown file. I used to just hit ctrl+F to search for the right section in the presentations.

**Comment by nfhavey** [comment]
This is great for scripts where you do huge things that you then want to not look at!

**Comment by tinghj17** [comment]
Thanks for sharing this outline feature. It would allow code reviewers to navigate a file more effectively!

**Comment by ecp9** [comment]
Thanks for sharing, this is something I wish I knew earlier!

**Comment by abarsch** [comment]
This will definitely help me out, thanks! The carpal tunnel doesnt need to get worse!

**Comment by aridimagiba** [comment]
Thank you so much for posting this! I've been working on a side project for my GSR and the rscript was getting too long. I was just talking about this issue with @clemencedarriet  not too long ago.  I will be definitely saving this link.
