### ISSUE TITLE
Unzip loop not working.

### ISSUE THREAD

**Issue by nfhavey** [Rucla-ed/rclass2#121]
Hello there!

When I try to implement the unzip loop, I get an error if I use unzip = "unzip" or if I don't:

> unzip(zipfile = file.path(data_dir,str_c(hd[1])), exdir = file.path(data_dir))
Warning message:
In unzip(zipfile = file.path(data_dir, str_c(hd[1])), exdir = file.path(data_dir)) :
  error 1 in extracting from zip file
> unzip(zipfile = file.path(data_dir,str_c(hd[1])), unzip = "unzip", exdir = file.path(data_dir))
Warning message:
In system2(unzip, args, stdout = NULL, stderr = NULL, invisible = TRUE) :
  '"unzip"' not found

When I try the full loop, I get the same error as when I exclude the unzip message:

for (i in 1:length(hd)) { #iterate through the hd vector
  writeLines(str_c("i=",i, "; hd[",i,"]=",hd[i], sep = ""))
  for (z in c("","Dict","_Stata")) { #iterate through "", "Dict, "_Stata"
    writeLines(str_c(z))
    unzip(zipfile = file.path(data_dir, str_c(hd[i]), unzip = "unzip", exdir = file.path(data_dir)))
  }}

In unzip(zipfile = file.path(data_dir, str_c(hd[i]), unzip = "unzip",  ... :
  error 1 in extracting from zip file

I don't really understand why this is happening.

**Comment by augias** [comment]
Looks to me like you've forgotten to combine the hd[i] string with your data_suffix?

**Comment by mpatricia01** [comment]
You are missing z in your unzip function where z iterates through "", "Dict", "_Stata". Have you tried different arguments for the unzip function? The default value is "internal". Does it work when you do not specify a value for unzip?

**Comment by nfhavey** [comment]
Thanks Fern!
