### ISSUE TITLE
Unzip function error

### ISSUE THREAD

**Issue by wangzi831** [Rucla-ed/rclass2#122]
Hi,
I'm having basically the same problem as #121 except none of the suggestions worked for me. It doesn't seem to be because of the suffix or the iteration as my attempts to run the single-line example code with the suffix also failed, as well as when I tried the default arguments for the unzip function. The iteration only returned the same warning message multiple times. Really look forward to figuring out why! @ozanj @mpatricia01 @cyouh95 

`
> unzip(zipfile = file.path(str_c(hd[1],data_suffix, sep = "")), unzip = "unzip", exdir = file.path(data_dir))
Warning message:
In system2(unzip, args, stdout = NULL, stderr = NULL, invisible = TRUE) :
  '"unzip"' not found
> unzip(zipfile = file.path(str_c(hd[1],data_suffix, sep = "")), unzip = "internal", exdir = file.path(data_dir))
Warning message:
In unzip(zipfile = file.path(str_c(hd[1], data_suffix, sep = "")),  :
  error 1 in extracting from zip file
`

**Comment by wangzi831** [comment]
I realized that I forgot to attach the data_dir in the second line, and it is indeed because of the default argument and it's working now. Sorry for the trouble and thanks for the helpful advice!

**Comment by ozanj** [comment]
I was just about to say this! glad you figured it out.
