### ISSUE TITLE
Step 5, Part V: val_label works outside of function, but not when called

### ISSUE THREAD

**Issue by augias** [Rucla-ed/rclass2#126]
Hey everyone, I have almost had it with function exceptionalism. 
@ozanj @cyouh95 @mpatricia01 

on the fifth step of the bonus section, I wrote my function to assign value labels to the dataframe, and something like df[temp_variable] works great in my var_label function, or when used just as a for loop. The code/loop below gives me a properly labelled "df" object outside the function brackets:

```
add_val_labels <- function(df, val_labels) {
  for (i in 1:nrow(val_labels)) {
    if (val_labels[i,2]!= "*") {
      temp_value <- as.numeric(val_labels[i,4])
      temp_var <- val_labels[i,3]
      writeLines(str_c("For value \"", temp_value, "\" in variable ", names(df[temp_var]), " assign value label \"", val_labels[i,5], "\""))
      print(typeof(temp_value)) #debugging
      print(typeof(df[temp_var])) #debugging
      val_label(df[temp_var], temp_value) <- val_labels[[i,5]]
    } else {
      temp_value <- val_labels[[i,4]]
      temp_var <- val_labels[i,3]
      writeLines(str_c("For value \"", temp_value, "\" in variable ", names(df[temp_var]), " assign value label \"", val_labels[i,5], "\""))
      print(typeof(temp_value)) #debugging
      print(typeof(df[temp_var])) #This shows a list in the for loop, but NULL after calling the function
      val_label(df[temp_var], temp_value) <- val_labels[i,5]
    }
  }
}
```

When called from the add_val_labels function on step six, R tells me that I am applying val_label to a NULL class object, and a typeof(df[temp_var]) indeed shows this is NULL. Whats up? It's definitely not a NULL type in for loop, nor in the previous add_var_label function so someone please catch the missing comma or whatever!

**Comment by cyouh95** [comment]
I think you might just need to return `df` from your function? Let us know if that works!

**Comment by augias** [comment]
Hi, Crystal
what a nightmare. that was it! 
although i struggled for a while placing return(df) in between the correct curly brackets for sure (had to be right outside the for loop). frustrating but a lesson I won't soon forget!
