### ISSUE TITLE
Potential ways to practice using issues

### ISSUE THREAD

**Issue by cyouh95** [Rucla-ed/rclass2#13]
Potential tasks for students to practice working w/ issues on their own student_lastname repos (could even be a regular part of problem sets):
* Create an issue titled "Homework 1"
* Make commit(s) (which would contain their hw files) that references the issue #
* Practice creating/adding labels that says "In Progress" or "Complete" to indicate progress on hw
* Self-assign issue to themselves while they're working on hw, then assign issue to Patricia when it's ready for grading
* Maybe Patricia can provide feedback on hw by commenting on the issue. It's also possible to refer to/embed lines of students' code: 
https://github.com/Rucla-ed/rclass2/blob/3f582990b06667a0c2b64b519ce36b2cb492c92f/lectures/github/github_lecture.Rmd#L687-L689
* Students can reply on issue if they have follow up questions, then close issue if all is resolved

The alternative is to have students post homework-related questions on rclass2 issues page. As mentioned in #6, I feel like the team discussion page might be more fitting. 

Since creating/posting an issue in itself isn't anything difficult, if students aren't working w/ other aspects of issues (e.g., referencing in commit, adding labels, assigning ppl) - then it seems like it'd be pretty much the same as just posting on the team discussion page...? But either way, I'm open to what you guys think is best!

**Comment by ozanj** [comment]
# I like these ideas. what do u think @mpatricia01?

**Comment by ozanj** [comment]
I'll let @mpatricia01 decide whether she thinks this makes sense or is too much work for her.

**Comment by ozanj** [comment]
i'm thinking that the idea for issues that @cyouh95 posted at beginning of this issue could be too much work for Patricia. 

how about this as the way issues are practiced in problem set 1 [issue #12]

students have to create an issue w/ label "question" [or something like that] and post a question like "what do you do to stay sane during Coronavirus" and assign the issue to three people in class that they do not know. and once they get three responses, they close the issue.
