### ISSUE TITLE
reading to do after class 1

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#14]
what reading should we assign after class 1?

think we can have a section in lecture about issues, but we probably won't get to it on first day. so probably better to just assign them some basic reading on using issues.

https://guides.github.com/features/issues/

what other things to assign them to read?

thought this one was interesting https://www.daolf.com/posts/git-series-part-1/

others?

**Comment by cyouh95** [comment]
Maybe this article, [What is Version Control](https://www.atlassian.com/git/tutorials/what-is-version-control), and parts of this [Getting Started](https://www.atlassian.com/git/tutorials/setting-up-a-repository) section? It's from [here](https://www.atlassian.com/git/tutorials), which contains other git tutorials as well.

There's also the main git [doc](https://git-scm.com/docs). Maybe we can let students explore those last 2 links to read more in-depth about some of the git commands covered in lecture?

**Comment by mpatricia01** [comment]
This is what I am thinking we should assign for reading to do after class 1:

1. [Mastering Issues](https://guides.github.com/features/issues/)

1. [What is version control](https://www.atlassian.com/git/tutorials/what-is-version-control)

1. [Setting up a repository ](https://www.atlassian.com/git/tutorials/setting-up-a-repository) 

1. [Guide to command line (terminal)](https://towardsdatascience.com/a-quick-guide-to-using-command-line-terminal-96815b97b955) (terminal and bash commands are similar)

1. Watch [video](https://www.youtube.com/watch?v=ephId3mYu9o&t) on relative and absolute file paths

**Comment by ozanj** [comment]
add "read syllabus" to assigned reading

what about this one [as sort of deeper intro to a core thing]: https://www.daolf.com/posts/git-series-part-1/

**Comment by ozanj** [comment]
for reading about command-line

should we assign this one [Patricia's] https://towardsdatascience.com/a-quick-guide-to-using-command-line-terminal-96815b97b955

or this one: https://www.educative.io/blog/bash-shell-command-cheat-sheet 
[they can skip creating custom commands]

**Comment by mpatricia01** [comment]
Okay. I can replace what is [version control reading](https://www.atlassian.com/git/tutorials/what-is-version-control) with https://www.daolf.com/posts/git-series-part-1/ and command line I suggested with https://www.educative.io/blog/bash-shell-command-cheat-sheet. 

So it would be:

1. Syllabus

1. [Mastering Issues](https://guides.github.com/features/issues/)

1. [Understanding git](https://www.daolf.com/posts/git-series-part-1/)

1. [Setting up a repository ](https://www.atlassian.com/git/tutorials/setting-up-a-repository) 

1. [Guide to command line](https://www.educative.io/blog/bash-shell-command-cheat-sheet) (skip creating custom commands)

1. Watch [video](https://www.youtube.com/watch?v=ephId3mYu9o&t) on relative and absolute file paths

**Comment by ozanj** [comment]
👍
