### ISSUE TITLE
lecture 1 edits

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#18]
@mpatricia01 @cyouh95 

Patricia - can you add the link to this video at beginning of lecture

https://www.dropbox.com/s/r4gij79tw8dx1zv/doyle_why_code_git.mp4?dl=0 

Will Doyle made it for us. it's 4 minutes long. I plan on playing it during class.

can it work for me to play a video from zoom with me as presenter?

**Comment by mpatricia01** [comment]
Added video to lecture. Not sure if you want it placed somewhere else or as a subheading. I think you can share the video by sharing your screen?
