### ISSUE TITLE
course content and lead roles

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#2]
Hey Patricia and Crystal,

can you two set up a meeting to discuss what you think course should cover, in what order, and for each topic/week who should work on it, who should take lead, etc.

I know that for me [and maybe for Patricia] this developing this course is an opportunity to learn stuff that I have been wanting to learn but haven't had the time. so if there are course topics that you want to take the lead on, I am all for that! for example, Patricia - I know you have been working on the string/text unit. but maybe you are also interested in taking lead on website. I want this to be a good learning opportunity for both of you so let me know.

Here is a link to google doc w/ some notes and chicken scratch on potential topics

https://docs.google.com/document/d/10pg9V0jRL8q3x0PS8Y_DAnvSg0PWZThr6Kb8crSGFgo/edit

also, helpful to check out list of topics from this class, but this is a semester long class and has different focus than ours I think

http://pablobarbera.com/POIR613/index.html

after you two meet and talk, we can set up a 3-way meeting to discuss next steps.

**Comment by mpatricia01** [comment]
Will do, @ozanj. 

@cyouh95 and I are scheduling a time to meet to talk about this and #1

**Comment by ozanj** [comment]
makes sense for Crystal to take the lead for the "programming" unit [iteration, writing functions, etc.].

can start by building from the lectures I wrote for the intro R class [note: I removed these from the fall 2019 class w/ the idea that we would introduce these topics during this class]

it's lectures 12 and 13
https://github.com/ozanj/rclass/tree/master/lectures
https://ozanj.github.io/rclass/resources/ 

BUT Crystal, I think you should fundamentally redesign these as you see fit. you have three weeks to teach students most essential stuff about iteration/writing functions. you decide what we should teach students, in what order, what applications, etc.
