### ISSUE TITLE
Delay in Approval for Twitter Access (APIs)

### ISSUE THREAD

**Issue by nfhavey** [Rucla-ed/rclass2#20]
As I mentioned, Twitter is experiencing a delay in approving access for Twitter applications / the API. If we're using this for class, folks should realistically apply now (regular timeline is a week or two, mine was returned in 3 days), as the delay might slow folks down. @ozanj @mpatricia01 @cyouh95

**Comment by mpatricia01** [comment]
Thanks @nfhavey. Will look into it!

**Comment by ozanj** [comment]
@nfhavey 
@mpatricia01 

Hey Nick - would you be willing to prepare a little step by step directions and explanation for students to get authorization for Twitter API? seems like students should do this soon so this tutorial would be super helpful. and we are like totally overwhelmed!

**Comment by nfhavey** [comment]
Happy to!

**Comment by ozanj** [comment]
Thanks Nick!

you and Patricia can work together to decide best way to deliver this to students. you could create a separate .Rmd file and we could require this as last step of next problem set and problem set directions would have link to little tutorial you create. or some other approach along those broad lines. appreciate you brother! o

**Comment by nfhavey** [comment]
I've already got the login details and whatnot sorted in an .Rmd, so I'll just create some slides / step by steps to actually getting access. Won't take too long!

**Comment by ozanj** [comment]
Thx nick!
