### ISSUE TITLE
Problem Set 1 - Nick Havey

### ISSUE THREAD

**Issue by nfhavey** [Rucla-ed/rclass2#21]
What's your favorite scary movie?

**Comment by lopezxochilth** [comment]
I actually strongly dislike scary movies. I can't do it. So unfortunately I don't have a favorite lol

**Comment by srvazquez-ucla** [comment]
I liked Hereditary, although I did not find it scary.

**Comment by abarsch** [comment]
Um, not a big scary movie person but if you count Alien that one!
