### ISSUE TITLE
Problem Set 1 - Bernard Reyes

### ISSUE THREAD

**Issue by BernardReyes** [Rucla-ed/rclass2#24]
How are you holding up during quarantine? 

@augias @laurenilano @Kei-qss

**Comment by augias** [comment]
good, good. perfecting my pizza technique
![pizza](https://user-images.githubusercontent.com/19480035/78196224-8d8b6400-7436-11ea-891b-1ad3f2b25109.jpeg)

**Comment by laurenilano** [comment]
@augias wow, very impressive!

i am hanging in there...trying to rest my eyes every so often as i feel i've been staring at screens 18 hours a day 📺

**Comment by Kei-qss** [comment]
I'm trying to make myself busy with watching Netflix, running around my
house, zooming with friends overseas, and cooking Japanese food..

=========================
Kei Tomaru / 渡丸 慶
TEL : +1-202-856-8337
Email : tomakei1@gmail.com
=========================

**Comment by mpatricia01** [comment]
Good question @BernardReyes ! Could you please close this issue.
