### ISSUE TITLE
Problem set 1- Lorraine Perales

### ISSUE THREAD

**Issue by lperales00** [Rucla-ed/rclass2#26]
What is your spirit animal?

**Comment by wangzi831** [comment]
I haven’t really thought about it but I guess it’s probably a Maine Coon lol

**Comment by laurenilano** [comment]
@lperales00 going off of the cat theme, i think i will say a siamese

@wangzi831 very creative lol...it inspired me to pick my cat's breed :)

**Comment by manie-byte** [comment]
A Pomeranian, you can tell from my profile photo haha! (it's my dog actually)

**Comment by lperales00** [comment]
> I haven’t really thought about it but I guess it’s probably a Maine Coon lol

I have a Maine Coon. Very social cats, love to be around guests.

**Comment by mpatricia01** [comment]
Thanks for your question @lperales00! Could you please close this issue?
