### ISSUE TITLE
Problem Set 1 - Zi Wang

### ISSUE THREAD

**Issue by wangzi831** [Rucla-ed/rclass2#27]
Hi, what is your favorite sport? @augias @BernardReyes @clemencedarriet

**Comment by augias** [comment]
Curling!

**Comment by BernardReyes** [comment]
Track & Field and basketball!

*Bernard Reyes, M.A.*
PhD Student, Higher Education and Organizational Change
Graduate School of Education & Information Studies
University of California, Los Angeles

**Comment by clemencedarriet** [comment]
ping pong - the only sport I'm halfway decent at.
