### ISSUE TITLE
Problem Set 1 - Irma Castañeda

### ISSUE THREAD

**Issue by irmacastaneda0822** [Rucla-ed/rclass2#28]
What's at-home workouts do you recommend? Any links to good YouTube videos or running plans?

**Comment by nfhavey** [comment]
Nike Run Club and Nike Training Club (apps) are free for premium right now! (And all of the Nike website is 25% off). You can select either a running plan and incorporate yoga / strength workouts or a strength plan based on your desired activity level and it creates one for you (mine is currently a 4 week run plan!)

**Comment by lopezxochilth** [comment]
I'm actually really curious to read what everyone else has to say! Here is the link to a youtube channel I enjoy working out with: https://www.youtube.com/user/blogilates

**Comment by dianadlopez** [comment]
Well if you enjoy the TV show Schitt's Creek, Alexis (Anne Murphy) just posted an instruction video of how to do her silly dance from the show. It probably won't be as fun out of context if you don't know the show, but her "stretches" starting at minute 5:00 will inspire ideas for making everyday stretches fun (even if they don't actually help you with a workout). [https://www.youtube.com/watch?v=w05xsio8zi8]

**Comment by irmacastaneda0822** [comment]
Thanks everyone for the recommendations! @dianadlopez I haven't seen Schitt's Creek, but I'll look it up...looking for new shows to keep me entertained during stay-at-home.
