### ISSUE TITLE
 Problem Set 1-Fernanda Castellon

### ISSUE THREAD

**Issue by fernandacastellon** [Rucla-ed/rclass2#29]
What was you dream career as a child?

**Comment by augias** [comment]
I think I wanted to be a chef (:>)=

**Comment by irmacastaneda0822** [comment]
I can't remember what I wanted to be in elementary school, but in middle and high school I wanted to be a lawyer. That dream definitely died haha

**Comment by ecp9** [comment]
So many things lol. Astronaut, paleontologist (blame jurassic park), and neurologist.
