### ISSUE TITLE
structure of lectures

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#3]
An issue I have been considering is how to change the structure of lectures [compared to my lectures from the intro R class].

My OCD style is very long and detailed lectures.

I would like to find a way to have shorter, high-level lectures so that there is more class time for students to work practice skills on their own on practical applications/challenges we give them.

USC prof Pablo Barbera: http://pablobarbera.com/teaching.html talks about this approach:
“My teaching generally follows a "learning-by-doing" approach, with short guided coding sessions followed by data challenges that prompt students to practice new methods and skills”

at the same time, I find the detailed examples from my lecture style helpful and students tell me they go back to those lectures months later [i do too].

i wonder if there is a way to have the best of both worlds.

high-level lectures that we give. our lecture slides also contain the detailed examples but perhaps these are skipped over, are in an appendix, or are embedded in lectures in another way (e.g., "gists")?

**Comment by mpatricia01** [comment]
@ozanj what do you mean in the last sentence "our lecture slides also contain the detailed examples but perhaps these are skipped over, are in an appendix, or are embedded in lectures in another way (e.g., "gists")?"

**Comment by ozanj** [comment]
you know how many of the lectures for the intro R class were very long (e.g., upwards of 50/60 slides). that's because the slides contained not only high-level explanation of the concept/syntax, but also lots of detailed examples. 

For the upcoming R class, we want to have shorter lectures and more time for students working on practical problems on their own. don't think this will be possible for the git/github unit [because we'll also be introducing ggplot, and dates/times too], but want to have lecture not more than 2 hours for classes starting in the text/string unit.

this suggests that our lectures should be more high-level. but I still like having the detail for students to refer to if they don't understand abstract syntax or for students to refer to after the course. so what is the best way to embed this detail somewhere in the lecture in such a way that we skip over this when I/you am giving the lecture during class time?

**Comment by mpatricia01** [comment]
I see. That makes sense. I think maybe we can include an appendix heading in the lecture and leave detail there for students to refer to or add details in footnotes? I did something like that for my regex lecture, but mostly to include where I got my sources from. The cool thing about footnotes is that you can click on it and it takes you to the bottom of the html file. 
<img width="1129" alt="Screen Shot 2020-03-24 at 3 38 25 PM" src="https://user-images.githubusercontent.com/33170829/77483501-82588880-6de5-11ea-9617-8714c33997c0.png">
<img width="1184" alt="Screen Shot 2020-03-24 at 3 38 14 PM" src="https://user-images.githubusercontent.com/33170829/77483511-8dabb400-6de5-11ea-8875-bf34483df41b.png">

**Comment by ozanj** [comment]
@mpatricia01 @cyouh95 

What about "collapsing" detailed examples w/ the default being that the detailed example is collapsed rather than uncollapsed.

see this: https://stanford.edu/~vbauer/teaching/websites.html#collapsing-sections
and this: https://getbootstrap.com/docs/4.3/components/collapse/

One potential concern: I would like students to be able to run the .Rmd files themselves if they want. not sure if including this functionality would make it more difficult for students. the post by https://stanford.edu/~vbauer/ suggests that the "Bootstrap library" is pre-loaded in RMarkdown, so maybe this wouldn't be an issue.

thoughts?

**Comment by cyouh95** [comment]
Just tested this out and it seems to work well - it doesn't affect running the R chunks in any way. The collapsibles don't come w/ any style by default though, so we'll just need to add some color/border to make it obvious that it is expandable and contains extra info. Other than that, I think this could definitely be an option!

**Comment by mpatricia01** [comment]
Can also try this code

`<details><summary>Detailed example</summary>
<p>

#### yes, even hidden code blocks!

```{r}
print("hello world!")
```
</p>
</details>`

From https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

**Comment by ozanj** [comment]
Great!

@mpatricia01 @cyouh95 

let's use these approaches to collapsing that you found. please add to lecture .Rmd code as you see fit and make comments to me about what code is doing so I understand. 

i'll consider this issue closed.
