### ISSUE TITLE
Problem Set 1- Xochilth Lopez

### ISSUE THREAD

**Issue by lopezxochilth** [Rucla-ed/rclass2#30]
What books (non-academic) do y'all recommend?

**Comment by srvazquez-ucla** [comment]
I'm currently reading Spirit Run which is about a guy who runs across north america (north to south direction) and tells the stories of the indigenous people he meets along the way.

**Comment by lperales00** [comment]
Anything Paulo Coelho. The last one I read was The Zahir about a husband looking for his lost/possibly kidnapped wife.

**Comment by mikerios96** [comment]
I started reading 'The Essential Wooden: A Lifetime of Lessons on Leaders and Leadership."

It's interesting! Nice to learn more about the famous John Wooden.
