### ISSUE TITLE
Problem Set 1 - Linli Zhou

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#31]
What's your favorite switch game!?

Mine is watching others' to play Animal Crossing and Zelda!!

**Comment by nfhavey** [comment]
I don't have a switch, but I play TFT / League of Legends!

**Comment by tinghj17** [comment]
Hi there! Mine is Overcooked 2!!

**Comment by srvazquez-ucla** [comment]
Currently playing Animal Crossing, but my favorite is definitely LoZ: Breath of the Wild
