### ISSUE TITLE
Problem Set 1- Estefania Castañeda Pérez

### ISSUE THREAD

**Issue by ecp9** [Rucla-ed/rclass2#32]
What is your favorite ice cream flavor?

@manie-byte  @laurenilano @BernardReyes

**Comment by laurenilano** [comment]
@ecp9 gotta go with guava

**Comment by BernardReyes** [comment]
The flavors change lol over time, but I like pistachio, mint chocolate
chip, and cookies and cream.

*Bernard Reyes, M.A.*
PhD Student, Higher Education and Organizational Change
Graduate School of Education & Information Studies
University of California, Los Angeles

**Comment by manie-byte** [comment]
Strawberry!!
