### ISSUE TITLE
Problem Set 1 - Tinghui Jiang

### ISSUE THREAD

**Issue by tinghj17** [Rucla-ed/rclass2#33]
What are your favorite YouTube channels?

**Comment by clemencedarriet** [comment]
binging with babish - he makes food from movies and shows, very entertaining!

**Comment by augias** [comment]
This one, or maybe Pasta Grannies https://www.youtube.com/channel/UC9fNs-US-P0OZ4zzWEzMsVQ

**Comment by dianadlopez** [comment]
Last Week Tonight with John Oliver is one of my favorites! 
https://www.youtube.com/user/LastWeekTonight

**Comment by abarsch** [comment]
I honestly don't go on Youtube regularly but I like NBA Desktop, which is also on youtube!
