### ISSUE TITLE
Problem Set 1 -- Lauren Ilano

### ISSUE THREAD

**Issue by laurenilano** [Rucla-ed/rclass2#34]
Anyone have any quarantine show/movie recommendations?

@rflores1180 @wangzi831  @fernandacastellon

**Comment by wangzi831** [comment]
I’m a huge lover of dark humor but during the quarantine I have been turning to and would recommend cute, relaxing comedy shows to have a good laugh (personally I’ve binge rewatched Brooklyn 99, the Office, and Silicon Valley). To find some peace, I’d recommend Wes Anderson and Paolo Sorrentino movies as they certainly helped me do so!
