### ISSUE TITLE
Problem Set 1 - Ariana Dimagiba

### ISSUE THREAD

**Issue by aridimagiba** [Rucla-ed/rclass2#36]
What are your top 2 favorite board games?

**Comment by abarsch** [comment]
Ooh, I like this! Top of 2 of all time are probably Settlers of Catan and Spirit Island

**Comment by lperales00** [comment]
To be honest, I am not much of a board gamer unless it involves drinking lol. Umm, maybe Loteria or chess? I don't know if those count as board games, but I will go with those.
