### ISSUE TITLE
Problem Set 1 - Diana Lopez

### ISSUE THREAD

**Issue by dianadlopez** [Rucla-ed/rclass2#37]
What is your favorite recipe to cook or bake?

**Comment by tinghj17** [comment]
My all-time favorite sweet: https://www.youtube.com/watch?v=GZA-9iifZfU&t=1s

Simply delicious!!

**Comment by irmacastaneda0822** [comment]
I love making homemade pizza. 

This is one of my favorite recipes: https://www.halfbakedharvest.com/mediterranean-roasted-red-pepper-pizza/

To make homemade pizza dough: https://bellyfull.net/quick-and-easy-pizza-dough/

**Comment by manie-byte** [comment]
I love sushi! Check this video: https://www.youtube.com/watch?v=RW7Rzas5mKI
 They always make some cute tiny food in a tiny little kitchen!

**Comment by dianadlopez** [comment]
Thank you for sharing your favorite recipes! I especially loved the tiny sushi video and hope to make all of these someday soon. -Diana
