### ISSUE TITLE
--set upstream, why?

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#39]
when "git push", why we would use "--set upstream"
I searched on google but those answers still sound confusing...

**Comment by ZhouLinli** [comment]
I am not sure what is Crystal's account name so can't assign this issue to her... just to let you know @mpatricia01  @ozanj

**Comment by ozanj** [comment]
@cyouh95 

Crystal - can you answer this question from Linli?

**Comment by mpatricia01** [comment]
Good question @ZhouLinli!

I think --set upstream is mostly when you are working with branches. So if you have a local branch you created and want to link your local branch to your remote branch. 

@cyouh95 correct me if I am wrong. 

These links might be useful.
https://git-scm.com/book/en/v2/Git-Branching-Remote-Branches
https://devconnected.com/how-to-set-upstream-branch-on-git/

**Comment by ZhouLinli** [comment]
this is really really helpful! thanks crystal and Patricia! @cyouh95 @mpatricia01
