### ISSUE TITLE
Problem Set 1 - Barsch

### ISSUE THREAD

**Issue by abarsch** [Rucla-ed/rclass2#40]
Have you seen any good movies recently?

**Comment by irmacastaneda0822** [comment]
I've started watching the Marvel movies. So far I've liked the Captain America movies! haha

**Comment by seanbeaton** [comment]
There is one good movie, pulp fiction

**Comment by seanbeaton** [comment]
well, I guess there are others.

**Comment by Kei-qss** [comment]
Minority Report, Whiplash and Crazy, Stupid, Love were all good!

**Comment by mikerios96** [comment]
I saw Onward recently! That Disney movie with Chris Pratt and Tom Holland...it was alright lol

**Comment by abarsch** [comment]
@seanbeaton Haha there are some others but what a good movie
