### ISSUE TITLE
Problem Set 1 - Michael Rios

### ISSUE THREAD

**Issue by mikerios96** [Rucla-ed/rclass2#41]
How have you stayed active during this time?

**Comment by abarsch** [comment]
I haven't haha I have actually been running more than usual, up to 2 miles every couple days

**Comment by irmacastaneda0822** [comment]
Haha same here! I've been trying to go on walks, but I'm trying to figure out a workout routine. My question for this problem set was actually about getting workout tips. See issue #28

**Comment by Kei-qss** [comment]
I've also been running around my house. Other than that, I'm enjoying trying new things like cooking new dishes (Japanese, Korean, Thai..), playing the guitar, and chatting with Alexa:)

**Comment by mpatricia01** [comment]
Thank for the question @mikerios96 ! Could you please close this issue?
