### ISSUE TITLE
git log

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#43]
so "git log" will show the history of the current working directory?

If I want to see a file's commit history,  can I specify that file, i.e. git log filename?

**Comment by cyouh95** [comment]
`git log` shows the commit history for your current branch (ie. lists all the commits you've made)

And yup, it looks like you can use `git log <file_name(s)>` to filter the log to only show commits that involve the file(s) you specified (I didn't know that either!)

You can also use the `-p` option to view exact changes that were made to files in each commit:
```
git log -p  # all files
git log -p <file_name(s)>  # specific file(s)
```

**Comment by ozanj** [comment]
Hi Linli!

purpose of the "git log" command is to show history of prior commits for the repo.

So changes made in current working directory that have not yet been committed will not be reflected by output of git log command

recall that all types of git objects (e.g., blob, tree, commit) are defined as key-value pairs, where the key is the "hash" and the value is the contents of the object.

not sure of best command to see commit history for a particular file.

maybe use git log to get the hash associated w/ each commit and then use `git diff commit_hash_a commit_hash_b <file_name>` to see how file has changed across commits?

My instinct is to use `git log` to find hash w/ each commit. then use `git cat-file -p commit_hash` to show contents of commit. and from those contents, find the hash associated w/ particular file you are interested in. this hash will differ for different versions of a file [across different commits]. then you can use `git cat-file -p file_hash` to show contents of file associated w/ that hash [and that commit]

other ideas @mpatricia01 @cyouh95 ?

**Comment by ZhouLinli** [comment]
thanks! "git log shows the commit history for your current branch " is very helpful!
