### ISSUE TITLE
use hash to find its corresponding filename

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#45]
in class, we learned how to find the hash of a file using "git hash-object <filename>"
however, conversely, if we already know the hash, how can we find the corresponding file_name or commit_name?

**Comment by nfhavey** [comment]
Hi Linli,

If you use git cat-file -p and the hash, it should show you the information you're interested in. This is sort of circular to me, so hopefully that helps. Ping me if it doesn't.

**Comment by ZhouLinli** [comment]
it seems does not work @nfhavey . here is the command and output
COMMAND
git hash-object 2181ac63f1c7d60bf91c7f28ceddd0873082971d
OUTPUT:
fatal: Cannot open '2181ac63f1c7d60bf91c7f28ceddd0873082971d': No such file or directory

**Comment by nfhavey** [comment]
Hi! 

That's because you're not using the proper code.

You should run git cat-file -p and the hash, not git hash-object (git hash object computes the SHA1 hash you're imputting, so it inherently won't run.)

**Comment by mpatricia01** [comment]
Thank you @nfhavey !

@ZhouLinli what do you mean by finding the file name or commit name? 

`git cat-file -p [hash]` will show you the content of the object. If you want to see the commit name maybe just use `git log`?

**Comment by ZhouLinli** [comment]
thanks @nfhavey  yes you're right i used the wrong command. so when i use "git cat-file -p <the hash>" it prints out the content of the object sucecsfully.

i wonder if there is a way to print out the name of the file, not just the content (-p) or size (-s) or type (-t)


@mpatricia01  by file name i just mean the name of the file corresponding to the hash.

**Comment by mpatricia01** [comment]
Hi @ZhouLinli,

If you just want to get the file name you could use the `git ls-files`command. It is similar to `ls`. You can add another argument to see `-c` cached, `-d`deleted, `-s` staged files, etc. See this link https://git-scm.com/docs/git-ls-files

**Comment by ZhouLinli** [comment]
Hi @mpatricia01 , the git ls-files command is helpful. I have a follow-up on this git ls-files command: I don't know why it does not work for my "zhou_ps1" directory (error msg: fatal: not a git repository) but works for my "zhou_ps1/scripts" directory. 

Besides, what I asked previously is actually how to use a "hash" to find out its corresponding "file name".

**Comment by mpatricia01** [comment]
@ZhouLinli , yes you have to set your working directory first for the command to work. If you have the hash, you can type something like this `git ls-tree [insert hash]`. This will show you the files in the tree. I think you have to set your working directory first. 
<img width="513" alt="Screen Shot 2020-04-09 at 12 49 13 PM" src="https://user-images.githubusercontent.com/33170829/78934861-854bae00-7a60-11ea-9d5c-8f8f83e0d074.png">

**Comment by cyouh95** [comment]
Agree w/ everything @nfhavey & @mpatricia01 wrote!

@ZhouLinli - To add to that:

According to [here](https://stackoverflow.com/a/23838584/6373540), it looks like `git rev-list --objects --all` lists out all hashes + corresponding file names in your repo, then you can use `grep` to filter for the specific hash you're looking for. So:

```
git rev-list --objects --all | grep <blob_hash>
```

Similarly for commits, I think you could do something like:

```
git log | grep -A 5 <commit_hash>
```

For your other question, maybe you've initiated your git repo in the `scripts` sub-directory instead of `zhou_ps1` (ie. ran `git init` in the `scripts` directory)? If you try running `ls -la` inside the `scripts` and `zhou_ps1` directories, which one contains the `.git/` folder?

**Comment by ZhouLinli** [comment]
> @ZhouLinli , yes you have to set your working directory first for the command to work. If you have the hash, you can type something like this `git ls-tree [insert hash]`. This will show you the files in the tree. I think you have to set your working directory first.
> <img alt="Screen Shot 2020-04-09 at 12 49 13 PM" width="513" src="https://user-images.githubusercontent.com/33170829/78934861-854bae00-7a60-11ea-9d5c-8f8f83e0d074.png">

thanks this is really helpful!

**Comment by ZhouLinli** [comment]
> Agree w/ everything @nfhavey & @mpatricia01 wrote!
> 
> @ZhouLinli - To add to that:
> 
> According to [here](https://stackoverflow.com/a/23838584/6373540), it looks like `git rev-list --objects --all` lists out all hashes + corresponding file names in your repo, then you can use `grep` to filter for the specific hash you're looking for. So:
> 
> ```
> git rev-list --objects --all | grep <blob_hash>
> ```
> 
> Similarly for commits, I think you could do something like:
> 
> ```
> git log | grep -A 5 <commit_hash>
> ```
> 
> For your other question, maybe you've initiated your git repo in the `scripts` sub-directory instead of `zhou_ps1` (ie. ran `git init` in the `scripts` directory)? If you try running `ls -la` inside the `scripts` and `zhou_ps1` directories, which one contains the `.git/` folder?

when i use "git rev-list --objects --all", indeed it shows me every file's hash and the file names. however, somehow I got TWO different hash for each file. In other words, the files all appear twice. Any ideas?
![image](https://user-images.githubusercontent.com/53378364/79080672-c72c5c80-7ccb-11ea-8bc4-cfc075180d4e.png)

**Comment by cyouh95** [comment]
@ZhouLinli I think that's to be expected! Each time you add/commit the file, it creates a separate blob object for it. 

Maybe try using `git cat-file -p <hash>` to print out the contents for each of the 2 versions of the file. You should see that one is how the file looked when you first committed it, and the other is how it looked when you next committed it, etc.

**Comment by ZhouLinli** [comment]
got it! thanks crytal!
