### ISSUE TITLE
commands to view the content of an object

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#47]
in-class we learned "cat <filename>" and "git cat-file <hash of a file or a directory>" to view the content of an object (either file or directory). 
Are there other commands to view the content of an object?

secondly, am I right on my statement above that "cat" only works for a **file** name while "git cat-file" works for any object's hash?

ps. I know if we put hash after "cat", it shows unreadable compressed texts, so probably means "cat" do not work well for hash...

**Comment by nfhavey** [comment]
Hi Linli!

You'll want to specify what you want to view. For the problem set you want content, type, and size.

git cat-file -t  (type)
git cat-file -s (size)
git cat-file -p (pretty prints the content)

To my understanding, cat only works if you have the file name (ex: cat README.txt) whereas git cat-file is for when you have the hash (ex: git cat-file -t 123456789).

cat does not work well for hashes! If you're having trouble identifying a hash, consider using git hash-object and the file name. 

Hope that helps! 

Nick

**Comment by ZhouLinli** [comment]
hi nick @nfhavey  thanks, yes, your answer helps to solve the second part of my question! 

any idea about "any other commands to view the content of an object apart from cat and git cat-file"

**Comment by mpatricia01** [comment]
Thank you @nfhavey ! This is really helpful.

@ZhouLinli cat is a command used in terminal and other command line interfaces. Whereas `git cat-file` is a command used for git. So you can use `cat` to view contents of an object whether you are using git/GitHub or not.  As far as your question about other commands to view content of an object, I am not sure, but this link might be helpful. 

https://unix.stackexchange.com/questions/86321/how-can-i-display-the-contents-of-a-text-file-on-the-command-line

**Comment by ZhouLinli** [comment]
thanks！
