### ISSUE TITLE
Bigger Picture of Git

### ISSUE THREAD

**Issue by mikerios96** [Rucla-ed/rclass2#49]
Hi Everyone, 

So I think I conceptually am following along with Git and Github. Although, I am confused about what the bigger picture of Git is? Is the entire premise making changes on your local machine and loading them into a centralized cloud/repository?

Thanks!

**Comment by tinghj17** [comment]
Hi there, 

From my understanding, apart from what you said, version control is also a big part of using Git. It allows you to make changes on different parts (branches) of the file (master) without damaging the file as a whole.

**Comment by ecp9** [comment]
a lot of people in my program use git, and I think the whole premise is to make data "transparent" so that others can either prove or falsify someone's work. I don't know if this answers your question--but  I understand git as a kind of sophisticated dropbox :P

**Comment by manie-byte** [comment]
Some of my friends who study computer science or work in tech companies also use Github to share or download open-source projects. I imagine that if one day we are more proficient in coding, we can create our own project or download Softwares developed by others on Github!
