### ISSUE TITLE
Question about the bash chunk in R

### ISSUE THREAD

**Issue by wangzi831** [Rucla-ed/rclass2#56]
The bash chunks worked fine after I ran the very helpful codes Professor provided last week, but they fail again every time I restart the computer or just the Rstudio, so I need to re-run those codes over and over again. Right now I saved an rmd file so that I can run those codes easily, but I'm still curious, is the whole bash situation normal? Will all the constant modifications to the PATH cause any problem? Thank you very much!

**Comment by clemencedarriet** [comment]
I am having the same issue where I need to re-run the r code before each session.

**Comment by ozanj** [comment]
@cyouh95 - would you look into this? I don't know why people would have to modify the PATH each time.

another option to try [for PC users]:

uninstall bash/git bash and then re-install following the directions here: 
https://happygitwithr.com/install-git.html

in particular, this is the most relevant text about options to choose when installing git bash: 

- "NOTE: When asked about “Adjusting your PATH environment”, make sure to select “Git from the command line and also from 3rd-party software”. Otherwise, we believe it is good to accept the defaults."

the "3rd party software" they referred to would include RStudio.

let me know if this overcomes the problem!

**Comment by cyouh95** [comment]
[Here](https://helpdeskgeek.com/windows-10/add-windows-path-environment-variable/)'s some steps for manually adding to the `PATH` variable on Windows (ie. adding `C:/Program Files/Git/bin`) - maybe this is worth a try!

**Comment by wangzi831** [comment]
The reinstallation didn't work but the manually adding method did! I restart the pc and the chunk is working fine now. Thank you so much for your help! @ozanj @cyouh95

**Comment by ozanj** [comment]
@cyouh95 - thanks for your solution!

a lot of students have had this problem and/or a related one w/ regard to the PATH and running bash from .Rmd file. 

@cyouh95 - could you create a "gist" or something similar w/ explanation of the problem, so helpful tips on code and links to helpful blog posts? we'll figure out where to put these gists later! no rush on this Crystal. within the next week or so.

**Comment by cyouh95** [comment]
Yay, glad it worked! @wangzi831 @ozanj 

Okay! I can try to put something together for this.

**Comment by ZhouLinli** [comment]
the link you gave to manually set PATH only works for PC but I have a MAC....

**Comment by ozanj** [comment]
on the error you get when you type "pwd" above: the commands above "pwd" are R commands but "pwd" is a bash command. so the error is likely that you are including a bash command within an R code chunk.

w/ respect to your question about how to find the path:

it looks like you are getting reasonable output when you run the R command Sys.getenv("PATH"). so is your question where is the PATH located on your computer (e.g., which file/folder is PATH located on? @cyouh95 - do you know?

w/ respect to the bash code chunk problem: there may be some characters not visible to the eye that are creating the problem. try adding and deleting space before and after the three ticks (or maybe deleting any indentation before the ticks).

note: for me, the first line of code in any bash code chunk I run is always changing directories to the git repo. I change to the root directory and then add relative filepath from the root, like this:

```{bash}
cd ~/documents/learning_git/git_branch

git branch

git push --set-upstream origin master
```

**Comment by cyouh95** [comment]
@ZhouLinli For Mac users, I don't think we should have any issues running bash, so you wouldn't need to worry about Ozan's comment [here](https://github.com/orgs/Rucla-ed/teams/announcements/discussions/3/comments/2) - unless there was something in particular that wasn't working for you? 

But as Ozan mentioned, it seems like you're getting reasonable output for `Sys.which('bash')` - so you should be good! You can also see from your output above that `/bin` (where your bash is located) is indeed part of your PATH. If you were to modify the PATH, it would be a different process than on Windows (you can do it via your Terminal)

**Comment by ZhouLinli** [comment]
@cyouh95  Thanks Crystal. But I still do not have the green arrow to "run current chunk". 

![image](https://user-images.githubusercontent.com/53378364/79496797-838f6680-7fdb-11ea-89e8-ddc3f5f32ef2.png)

**Comment by cyouh95** [comment]
@ZhouLinli Hm, if you try creating a brand new .Rmd file and add a bash chunk there, does it make any difference?

Or, do any of the below ways work?
- Highlight the code inside the bash chunk and hit `cmd` + `Enter` on your keyboard
- Highlight the code inside the bash chunk and click under menu bar > `Code` > `Run Selected Line(s)`
- Place your cursor inside the bash chunk and click under menu bar > `Code` > `Run Region` > `Run Current Chunk`
- Place your cursor inside the R chunk you have in the above example, and click under menu bar > `Code` > `Run Region` > `Run All Chunks Above`

Also, what version of R do you have?

**Comment by ZhouLinli** [comment]
@cyouh95  thanks for those "run chunk" suggestions. but I think the problem might not be just finding a way to run the chunk, but that it seems my r studio does not recognize the bash chunk. 
the missing green arrow may represent my {bash} chunk is simply not recognized. 

I tried that cmd+enter which I've been always used to run r chunks but it just does not work for the bash chunk. 
<img width="494" alt="Screen Shot 2020-04-18 at 1 28 48 AM" src="https://user-images.githubusercontent.com/53378364/79632434-f7348f00-8113-11ea-94c9-26fc5b7432b8.png">

**Comment by cyouh95** [comment]
Weird! You're right - it looks like that bash chunk is being interpreted as R code...

What if you wrote `{bash, engine.path = '/bin/bash'}` instead of `{bash}`?

**Comment by ZhouLinli** [comment]
thanks @cyouh95  but still the same error message. 
maybe @mpatricia01 and @ozanj  can help?

**Comment by ozanj** [comment]
I experienced the same thing where some code chunks mor recognized as code
chunks when I was doing the problem set for myself. I played around with
spacing/tabs, and created new code chunks and eventually got them to work,
but never could figure out what the problem was in the first place
