### ISSUE TITLE
Need help creating legend on ggplot

### ISSUE THREAD

**Issue by lopezxochilth** [Rucla-ed/rclass2#59]
I can't seem to use the code: **scale_color_discrete()** to create a legend for the question asking  us to plot the "visits" in color. Here is my current code: 

ggplot(df, aes(x = total_students, y = avgmedian_inc_2564, color = visits_by_110635)) +
  geom_point() +
  print(labs(x = "Total Enrollment", y = "Median Household Income")) 

Thanks!

**Comment by mpatricia01** [comment]
Good question @lopezxochilth !

You might want to use the dummy variable `visited` we created in the previous problem set for whether a school receives a visit. 

You do not need the print function to label the x and y axes. It would look something like this `xlab("x variable") + ylab("y variable")`. This [link](http://r-statistics.co/ggplot2-cheatsheet.html) might be helpful for the scale_color_discrete() function.  It would look something like this `scale_color_discrete(name = "name of legend", labels = c("label 1", "label 2"))`

Your plot should look something like this
`ggplot(data = df, aes(x = x, y = y, color = as.factor(color variable))) +
geom_point() +
xlab("x variable") + ylab("y variable") +
scale_color_discrete(name = "name of legend", labels = c("label 1", "label 2"))`

**Comment by augias** [comment]
Just wanted to chime in here that my use of labels and the coloring looks wildly different (and shows how wide open R and tidyverse syntax can be:

ggplot(data=df_school_2) + 
  geom_point(mapping = aes(x = total_students, y = avgmedian_inc_2564, color = as.factor(visited))) +
  labs(x = "Total High School Enrollment", y = "Average Median Income", color = "Visited by UC Berkeley")

in this case, putting the color legend into the labs() function (labels) let me sidestep needing scale_color_discrete() and xlab() ylab()
