### ISSUE TITLE
Settings for remote repositories

### ISSUE THREAD

**Issue by Kei-qss** [Rucla-ed/rclass2#63]
Hello! Please let me check about two settings when making a new remote repository.

- Private vs Public
Private repositories can be seen by owners of the group (so in Rucla-ed, only Prof and TAs)?
Public repositories can be seen by anybody including non-members of the group?

- README
When should we start a remote repository with a README? I am not so sure when/how to use it.

Thank you in advance!

@ozanj @mpatricia01 @cyouh95

**Comment by cyouh95** [comment]
@Kei-qss For the first bullet - yup, I believe that is the case! But for private repos, we could also give access to certain users/teams if we wanted.

For the second - please see #61 and let us know if you'd like further clarification.

**Comment by Kei-qss** [comment]
Thank you, Cristal!
