### ISSUE TITLE
Origin -- the remote repo name ?

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#68]
when we create a new repo, we name it, for example, "lastname_ps3". we use the same name at local and remote when creating the repo. Then our local and remote repo are both "lastname_ps3". 

however, we learned that "ORIGIN" is the remote repo name?  but the repo name should be "lastname_ps3", right?  what's the difference? Why it seems there are two names for the remote repo?

**Comment by ozanj** [comment]
the repo name is repo_ps3 or whatever u wanna call it. the "remote" is short for the "remote url". by convention, the remote is named "origin" but u could name it whatever u not. let's say we named it "remote_ps3" then that is the name that is essentially a pointer for the actual url where ur remote repo is stored

**Comment by ZhouLinli** [comment]
thanks!
