### ISSUE TITLE
Problem set Question (Resolve merge conflict & push to remote repository)

### ISSUE THREAD

**Issue by laurenilano** [Rucla-ed/rclass2#69]
Just a few questions about the problem set. In Part III Question 10 when you resolve the merge conflict on the dev branch, I made the changes in the "problemset3.R" file and then just added / committed the file so if I understand that correctly, that means that I selected only the changes I wanted from the master branch merge attempt and "saved" (committed) those into my dev branch? 

~~When we finally pushed the dev branch to the remote repository, I can see all my files, but my master branch on github is way behind because the last push I did was much earlier in the assignment. Is that correct or should I also push the master branch to my remote repository?~~ 
[Nevermind, when I wrote this I had not done Part VI--committed Rmd and pushed master in Part VI)

**Comment by cyouh95** [comment]
@laurenilano Yes, I think you have the right idea! When you manually edited the conflicted file during the merge, you've chosen to keep the master branch's version of the line, and then committed that to the dev branch/completed the merge.
