### ISSUE TITLE
add .Rproj to .gitignore

### ISSUE THREAD

**Issue by ZhouLinli** [Rucla-ed/rclass2#76]
1. when we create a repo we have a chance to add .gitignore. but if we already created a repo, how can we add more .gitignore? 
- do we just edit the ".gitignore" file on Github? (if yes, the .gitigore file looks complicated to edit...where should I put the new .Rproj..?)
- or should we do sth in the terminal (and do we git add, commit, and push?)?

2. when the .gitignore is added, how do other members "git pull", should we type "git pull .gitignore" on our local repo (that we've just cloned)?

3. besides, can we make changes on our individual branch first and git pull this .gitigore update later?

**Comment by ozanj** [comment]
good questions! I'll answer in CAPS

when we create a repo we have a chance to add .gitignore. but if we already created a repo, how can we add more .gitignore? [YOU COULD ADD IT JUST BE CREATING A NEW TEXT FILE NAMED ".gitignore" AND PUT IT INTO THE ROOT DIRECTORY OF YOUR LOCAL REPO]

do we just edit the ".gitignore" file on Github? (if yes, the .gitigore file looks complicated to edit...where should I put the new .Rproj..?) [YOU CAN EDIT IT ON GITHUB. BUT I THINK BETTER TO EDIT IT ON A TEXT EDITOR ON YOUR LOCAL MACHINE. THIS WILL BE EDITING ON A LOCAL BRANCH AND THEN YOU COULD PUSH TO MASTER

or should we do sth in the terminal (and do we git add, commit, and push?)? [YES]

when the .gitignore is added, how do other members "git pull", should we type "git pull .gitignore" on our local repo (that we've just cloned)? GIT PULL IS TO PULL ALL CHANGES FROM REMOTE REPO TO LOCAL REPO. ONE BASIC FLOW (IN ADDITION TO CREATING FROM GITHUB WHEN REPO IS FIRST CREATED) WOULD BE FOR ONE PERSON TO CREATE .gitignore AND ADD IT TO TRACKED FILES AND THEN COMMIT TO LOCAL REPO AND THEN PUSH TO REMOTE REPO. OR ONE PERSON COULD EDIT EXISTING .gitignore AND COMMIT AND PUSH. 

.gitignore IS JUST A TEXT FILE AND IS NOW DIFFERENT FROM A .R SCRIPT W/ RESPECT TO ADD/COMMIT/PUSH RULES WE HAVE ALREADY LEARNED. 

note you could add the .gitignore to the list of files to be ignore within your .gitignore. this would stop .gitignore from being included in git commits. this is the approach to take if everyone wants to have their own .gitignore on their local machine that may different from others on the repo, but definitely no need to do this.

besides, can we make changes on our individual branch first and git pull this .gitigore update later?

**Comment by ZhouLinli** [comment]
thanks @ozanj 
you said ".gitignore IS JUST A TEXT FILE AND IS NOW DIFFERENT FROM A .R SCRIPT W/ RESPECT TO ADD/COMMIT/PUSH RULES WE HAVE ALREADY LEARNED." so do you mean, if we edited .gitignore file, we do not need to git add/commit/push?

Another follow up: 
the .gitignore file seems very complicated (we already have .R added in this .gitignore)... any guidance (e.g. format guidance) of how to edit it, specifically to add .Rproj to .gitignore?

**Comment by ozanj** [comment]
sorry, I mean to say "no different from a .R script w/ respect to add/commit push rules"

this means that if you make edits to .gitignore, we can add the changes, commit them, and push to remote repo so others have the same changes.

w/ respect to your follow up,
I forgot that creating a new rproject automatically creates a .gitignore file. yes, there are a lot of things in that .gitignore that we haven't discussed. but you could just delete all those and start from scratch.

good questions!!!

**Comment by ZhouLinli** [comment]
ok thanks!!
