### ISSUE TITLE
Disappearing files on my local machine

### ISSUE THREAD

**Issue by tinghj17** [Rucla-ed/rclass2#79]
Hello, I have a question about git pull and switch branch. 

For part 4, I created custom.RDS and custom.png under branch Jiang_plot and successfully pushed them on github. After doing these steps, I switched back to branch dev_tj and did some git pull and git push to finish part 3 question 4. Somehow, custom.RDS and custom.png disappeared on my local machine.

Could you please give me some hints about why this happened?

Thank you for your help!

@ozanj @cyouh95 @mpatricia01

**Comment by augias** [comment]
Hola, when you switch branches, your file system will actually reflect the committed files of any branch you change into. If you switch back to Jiang_plot, do your files return?

If i am in branch dev, and I create a custom plot, it stays in the dev branch. If i switch to master, master has no custom plots in its commit history and changing branches makes the plot disappear until you return to the branch where that file was created and added/committed.  

It's also pretty dangerous! Best practice is to never switch branches until you have committed any/all changes to your current branch.

**Comment by irmacastaneda0822** [comment]
I learned this the hard way! On a previous problem set, I accidentally switched from a branch to master without committing the files. When I returned to the branch later on, I couldn't find my files :(

When this happens, is there any way to recover the lost files?
@cyouh95 @mpatricia01 @ozanj
