### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by ozanj** [Rucla-ed/rclass2#8]
spend 5-10 minutes on Zoom google document Patricia created [Thx!]

https://docs.google.com/document/d/14WC7-bJrxwa-pcnFT5Tj19UoHrid9YYJXRo3QHknMbM/edit

are you two free today 3:30-4PM pacific for a quick call about how we should use zoom for class?

**Comment by cyouh95** [comment]
3:30-4p today works for me!
