### ISSUE TITLE
Changing observation #s when pulling in twitter data

### ISSUE THREAD

**Issue by augias** [Rucla-ed/rclass2#87]
My teammate @clemencedarriet and I were seeing how total row numbers kept changing as we pulled data from twitter on the COLA request. One moment there were ~720, at another ~780, and this afternoon about ~730 made it into my final data set. 

I may have missed the explanation given during lecture, and would appreciate understanding what's going on here. Although we specified 1000 lines to pull from twitter's API, we did not match that. So do we assume there aren't that many tweets made by our user set? What about the fluctuations in total observations? Are these users deleting their tweets and/or getting deleted?

**Comment by mpatricia01** [comment]
Hi @augias !

Good questions. The `n` argument in the `search_tweets()` function specifies the desired tweets we want returned. Ideally we would like 1,000, but your intuition is correct. It could be that the user set we defined does not have a total of 1,000 tweets or that they do not have 1,000 tweets in the last 6-9 days. As far as your question about the data frame returning different number of observations, I am not entirely sure. It could be that tweets are being deleted. Another possibility is that not all the tweets were returned. For example, I ran the code again and I got a data frame of 733 observations, however the verbose message I received said the following: 
<img width="940" alt="Screen Shot 2020-04-27 at 3 10 12 PM" src="https://user-images.githubusercontent.com/33170829/80426241-2a0c1f00-889a-11ea-8011-74fdb562f220.png">

It could be that my data frame does not include all tweets I queried. When you run the command again do you get a similar message? If so, what does it say.

**Comment by augias** [comment]
Exactly the same, and I forgot to mention in the op. My output and Clemence's both  showed the query ending at 90% just like your screenshot. I also got 733 just now to test. but my exercise this afternoon has 733 obs. Seems like deleted tweets.

**Comment by clemencedarriet** [comment]
I just tried it again and it had 777 obs and went to 100%, but earlier I experienced the same phenomenon that Fernando is describing where it wasn't going to 100% but actually had more tweets (796).

**Comment by mpatricia01** [comment]
That is really odd. I'll try to figure out why that is.

**Comment by aridimagiba** [comment]
I was able to pull 1000 tweets today for COLA request. It could be related to the fact to day is May Day where there are actions to support workers. It just a thought.
