### ISSUE TITLE
Does Twitter_handle refer to screen_name?

### ISSUE THREAD

**Issue by tinghj17** [Rucla-ed/rclass2#93]
Hello,

I have a question about Part 2, question 7. Does Twitter_handle refer to screen_name or user_id? I am kind of confused here.

Thanks for your clarification.

@ozanj @mpatricia01 @cyouh95

**Comment by mpatricia01** [comment]
Hi @tinghj17 ,

Twitter handle refers to screen_name. Let me know if you have any more questions.

**Comment by ozanj** [comment]
screen_name
