### ISSUE TITLE
Lecture Slide -Strings & Datetimes

### ISSUE THREAD

**Issue by Kei-qss** [Rucla-ed/rclass2#95]
This time I especially enjoyed learning how to extract data from Twitter!

At the beginning of 5.2 Date/time object components in the lecture slide, the following lubridate functions might be typos.

min(): Minute => minute(): Minute
sec(): Second => second(): Second

Thank you always!

@ozanj @cyouh95 @mpatricia01

**Comment by ozanj** [comment]
Thank you @Kei-qss !!

Would you like to submit a pull request to fix the error?
