### ISSUE TITLE
clarification of ps6 question

### ISSUE THREAD

**Issue by wangzi831** [Rucla-ed/rclass2#99]
It seems intuitive but I just want to double check - do the questions that ask us to add a column has_match to the data frame cola_df2 using str_detect() (starting from Part III: Regular expressions, Match Characters, 2.(C)) want us to use "text" as the string instead of all or other variables in the data frame? Thanks!
@cyouh95 @mpatricia01 @ozanj

**Comment by ozanj** [comment]
Yes!

for part c of those questions the data frame is `cola_df2` and the variable within `cola_df2` that you will be working with is called `text`

so you can imagine a pipe that has stuff like

`cola_df2 %>% mutate(
  has_match = str_detect(string = text, pattern = regex("<string pattern you are looking for>"))
)

did that answer your question?

**Comment by wangzi831** [comment]
Another unrelated question that I'm curious about, not sure if I missed this in class: when we do `str_count(c(".a.aa.aaa", "abbaab"), 'a?') ` , it returns counts of 10 and 7, while only str_count this string returns counts of 9 and 6, so where is the extra character located?

**Comment by wangzi831** [comment]
> 
> 
> Yes!
> 
> for part c of those questions the data frame is `cola_df2` and the variable within `cola_df2` that you will be working with is called `text`
> 
> so you can imagine a pipe that has stuff like
> 
> `cola_df2 %>% mutate(
> has_match = str_detect(string = text, pattern = regex(""))
> )
> 
> did that answer your question?

Yes! Thank you very much!

**Comment by ozanj** [comment]
> Another unrelated question that I'm curious about, not sure if I missed this in class: when we do `str_count(c(".a.aa.aaa", "abbaab"), 'a?') ` , it returns counts of 10 and 7, while only str_count this string without specific condition returns counts of 9 and 6, so where is the extra character located?

the default value for the `pattern` argument is `pattern = ""`

try running below code and experimenting w/ it and hopefully this will help you understand why the difference. 

```
#pattern = "a?" which equals matching with "a" zero or one times
str_count(string = c(".a.aa.aaa", "abbaab"), pattern = "a?")
str_view_all(string = c(".a.aa.aaa", "abbaab"), pattern = "a?")

#pattern = "". which I think just matches to each individual character in the element
str_count(string = c(".a.aa.aaa", "abbaab"), pattern = "")
str_view_all(string = c(".a.aa.aaa", "abbaab"), pattern = "")
str_length(string = c(".a.aa.aaa", "abbaab"))
```
